#!/bin/bash

LAVANDER='0xffb4befe'
MAUVE='0xffe856d6'

options=(
	style=round
	width=5.0
	hidpi=on
  active_color="gradient(top_left=$LAVANDER,bottom_right=$MAUVE)"
  inactive_color="glow(0xff585b70)"
)

borders "${options[@]}"
