# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = uwsm-app -- variety
exec-once = printf %s\n "$HYPRLAND_INSTANCE_SIGNATURE" >> /tmp/his.log
# exec-once = uwsm-app -- flameshot # if enabled i see it twice in the tray
exec-once = uwsm-app -- nm-applet
exec-once = uwsm-app -- flameshot
exec-once = uwsm-app -- nm-applet
