general {
    # Disable automatic locking; idle should only start the screensaver.
    lock_cmd = true
    before_sleep_cmd = true
    after_sleep_cmd = sleep 1 && omarchy-system-wake                 # delay for PAM readiness, then turn on display.
    inhibit_sleep = 0
}

# Start screensaver after 2.5 minutes
listener {
    timeout = 150
    on-timeout = pidof hyprlock || omarchy-launch-screensaver
}
