exec_always --no-startup-id xinput set-prop pointer:"Logitech MX Master 3" "libinput Natural Scrolling Enabled" 1
exec_always --no-startup-id setxkbmap it -variant us
#exec_always --no-startup-id xmodmap ~/.Xmodmap
exec_always --no-startup-id setxkbmap --option caps:nocaps
exec_always --no-startup-id xcape -e 'Control_L=Escape'


