# Set portrait orientation for the monitor DVI-D-0
exec_always --no-startup-id xrandr --output DVI-D-0 --rotate left

# Start the compositor picom. The config file is at ~/.config/picom/picom.conf
exec_always --no-startup-id picom -b

# Start XDG autostart .desktop files using dex. See also
# https://wiki.archlinux.org/index.php/XDG_Autostart
exec --no-startup-id dex --autostart --environment i3

# The combination of xss-lock, nm-applet and pactl is a popular choice, so
# they are included here as an example. Modify as you see fit.

# xss-lock grabs a logind suspend inhibit lock and will use i3lock to lock the
# screen before suspend. Use loginctl lock-session to lock your screen.
exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork

# NetworkManager is the most popular way to manage wireless networks on Linux,
# and nm-applet is a desktop environment-independent system tray GUI for it.
exec --no-startup-id nm-applet

exec --no-startup-id ulauncher --hide-window --no-window-shadow
exec --no-startup-id variety
exec --no-startup-id nextcloud --background
exec --no-startup-id /opt/1Password/1password --silent
exec_always --no-startup-id flameshot 
exec_always --no-startup-id pactl set-default-sink alsa_output.pci-0000_03_00.1.hdmi-surround71.2
# exec --no-startup-id qt5ct

exec_always --no-startup-id xset s off
exec_always --no-startup-id xset -dpms
exec_always --no-startup-id xset s noblank
