#  List of supported fonts: `kitty : +list-fonts`
font_family       JetBrainsMono Nerd Font Mono Light
bold_font         JetBrainsMono Nerd Font Mono Bold
italic_font       JetBrainsMono Nerd Font Mono Light Italic
bold_italic_font  JetBrainsMono Nerd Font Mono Bold Italic

#: Font size (in pts)
font_size 24.0

disable_ligatures cursor

# Background opacity, 0.0 to 1.0
background_opacity 0.8

dynamic_background_opacity yes

macos_option_as_alt left

